update preprocessing threads and add finalize to Makefile

diff --git a/preprocessing/Makefile b/preprocessing/Makefile
--- a/preprocessing/Makefile
+++ b/preprocessing/Makefile
@@ -50,3 +50,125 @@ clean-all: clean clean-output clean-work
 	rm -f *.png
 	rm -f trace*.txt*
 	rm -f *.html*
+
+
+
+# ~~~~~ FINALIZE ~~~~~ #
+# steps for finalizing the Nextflow pipeline output 'work' directory
+#  Work dir contains subdirectories with intermediary files created when executing pipeline
+#  along with command execution logs, etc
+#  logs should be saved, along with a record of the contents of each subdir
+#  files in the 'publishDir' are often symlinked to items in the 'work' dir;
+#  these symlinks should be replaced with copies of the original file
+#  all files in the 'work' dir should be removed, except for the log files
+#
+#  Makefile configured for parallel processing of files
+#
+#  run with `make finalize -j8`
+
+# Nextflow "publishDir" directory of files to keep
+publishDir:=output
+# Nextflow "work" directory
+workDir:=work
+TRACEFILE:=trace.txt
+
+# remove extraneous work dirs
+# resolve publishDir output symlinks
+# write work 'ls' files
+# create work dir file stubs
+finalize:
+	$(MAKE) finalize-work-rm
+	$(MAKE) finalize-output
+	$(MAKE) finalize-work-ls
+	$(MAKE) finalize-work-stubs
+
+## ~~~ convert all symlinks to their linked items ~~~ ##
+# symlinks in the publishDir to convert to files
+publishDirLinks:=
+FIND_publishDirLinks:=
+ifneq ($(FIND_publishDirLinks),)
+publishDirLinks:=$(shell find $(publishDir)/ -type l)
+endif
+finalize-output:
+	@echo ">>> Converting symlinks in output dir '$(publishDir)' to their targets..."
+	$(MAKE) finalize-output-recurse FIND_publishDirLinks=1
+finalize-output-recurse: $(publishDirLinks)
+	find $(publishDir)/ -type l
+# convert all symlinks to their linked items
+$(publishDirLinks):
+	@ { \
+	destination="$@"; \
+	sourcepath="$$(python -c 'import os; print(os.path.realpath("$@"))')" ; \
+	if [ ! -e "$${sourcepath}" ]; then echo "ERROR: Source does not exist: $${sourcepath}; deleting link $${destination}"; rm -f "$${destination}"; \
+	elif [ -f "$${sourcepath}" ]; then rsync -va "$$sourcepath" "$$destination" ; \
+	elif [ -d "$${sourcepath}" ]; then { \
+	timestamp="$$(date +%s)" ; \
+	tmpdir="$${destination}.$${timestamp}" ; \
+	rsync -va "$${sourcepath}/" "$${tmpdir}" && \
+	rm -f "$${destination}" && \
+	mv "$${tmpdir}" "$${destination}" ; } ; \
+	fi ; }
+.PHONY: $(publishDirLinks)
+
+
+## ~~~ write list of files in each subdir to file '.ls.txt' ~~~ ##
+# subdirs in the 'work' dir
+NXFWORKSUBDIRS:=
+FIND_NXFWORKSUBDIRS:=
+ifneq ($(FIND_NXFWORKSUBDIRS),)
+NXFWORKSUBDIRS:=$(shell find "$(workDir)/" -maxdepth 2 -mindepth 2)
+endif
+# file to write 'ls' contents of 'work' subdirs to
+LSFILE:=.ls.txt
+finalize-work-ls:
+	@echo ">>> Writing list of directory contents for each subdir in Nextflow work directory '$(workDir)'..."
+	$(MAKE) finalize-work-ls-recurse FIND_NXFWORKSUBDIRS=1
+finalize-work-ls-recurse: $(NXFWORKSUBDIRS)
+# print the 'ls' contents of each subdir to a file, or delete the subdir
+$(NXFWORKSUBDIRS):
+	@ls_file="$@/$(LSFILE)" ; \
+	echo ">>> Writing file list: $${ls_file}" ; \
+	ls -1 "$@" > "$${ls_file}"
+.PHONY: $(NXFWORKSUBDIRS)
+
+
+
+## ~~~ replace all files in 'work' dirs with empty file stubs ~~~ ##
+NXFWORKFILES:=
+FIND_NXFWORKFILES:=
+# files in work subdirs to keep
+LSFILEREGEX:=\.ls\.txt
+NXFWORKFILES:='.command.begin|.command.err|.command.log|.command.out|.command.run|.command.sh|.command.stub|.command.trace|.exitcode|$(LSFILE)'
+NXFWORKFILESREGEX:='.*\.command\.begin\|.*\.command\.err\|.*\.command\.log\|.*\.command\.out\|.*\.command\.run\|.*\.command\.sh\|.*\.command\.stub\|.*\.command\.trace\|.*\.exitcode\|.*$(LSFILEREGEX)'
+ifneq ($(FIND_NXFWORKFILES),)
+NXFWORKFILES:=$(shell find -P "$(workDir)/" -type f ! -regex $(NXFWORKFILESREGEX))
+endif
+finalize-work-stubs:
+	$(MAKE) finalize-work-stubs-recurse FIND_NXFWORKFILES=1
+finalize-work-stubs-recurse: $(NXFWORKFILES)
+$(NXFWORKFILES):
+	@printf '>>> Creating file stub: $@\n' && rm -f "$@" && touch "$@"
+.PHONY: $(NXFWORKFILES)
+
+
+## ~~~ remove 'work' subdirs that are not in the latest trace file (e.g. most previous run) ~~~ ##
+# subdirs in the 'work' dir
+NXFWORKSUBDIRSRM:=
+FIND_NXFWORKSUBDIRSRM:=
+# regex from the hashes of tasks in the tracefile to match against work subdirs
+HASHPATTERN:=
+ifneq ($(FIND_NXFWORKSUBDIRSRM),)
+NXFWORKSUBDIRSRM:=$(shell find "$(workDir)/" -maxdepth 2 -mindepth 2)
+HASHPATTERN:=$(shell python -c 'import csv; reader = csv.DictReader(open("$(TRACEFILE)"), delimiter = "\t"); print("|".join([row["hash"] for row in reader]))')
+endif
+finalize-work-rm:
+	@echo ">>> Removing subdirs in Nextflow work directory '$(workDir)' which are not included in Nextflow trace file '$(TRACEFILE)'..."
+	$(MAKE) finalize-work-rm-recurse FIND_NXFWORKSUBDIRSRM=1
+finalize-work-rm-recurse: $(NXFWORKSUBDIRSRM)
+# remove the subdir if its not listed in the trace hashes
+$(NXFWORKSUBDIRSRM):
+	@if [ ! "$$(echo '$@' | grep -q -E "$(HASHPATTERN)"; echo $$? )" -eq 0 ]; then \
+	echo ">>> Removing subdir: $@" ; \
+	rm -rf "$@" ; \
+	fi
+.PHONY: $(NXFWORKSUBDIRSRM)
